### ISSUE TITLE
Ebuild request for decaf-emu

### ISSUE THREAD

**Issue by bell07** [Tatsh/tatsh-overlay#103]
I wonder you do not have the decaf-emu (WII-U Emulator) in your overlay ;-)

https://github.com/decaf-emu/decaf-emu

**Comment by Tatsh** [comment]
I did have it for a time but does this emulator really do anything yet?

**Comment by bell07** [comment]
You are right :-( Compiled manually and started "Super Mario 3D World". The game starts, but bad performance and crash on profile creation :-(
