### ISSUE TITLE
x11-misc/rom-properties: Missed USE-Dependency

### ISSUE THREAD

**Issue by bell07** [Tatsh/tatsh-overlay#105]
rom-properties requires enabled USE="curl" in xfce-extra/tumbler to work in xfce.

In [my ebuild](https://github.com/bell07/gentoo-bell07_overlay/blob/master/media-plugins/rom-properties/rom-properties-1.8.2.ebuild) I solved it with `DEPEND="thunar? ( xfce-extra/tumbler[curl] )"`. Now I decided to use your ebuild. 

Unsure if the gtk+:2 dependency is still valid for xfce. Thunar uses Gtk-3 in the meantime. 
The dependency graph `emerge -evpt xfce-extra/tumbler` contains gtk+:2 and gtk+:3 in output, so I think you can replace
`xfce? ( x11-libs/gtk+:2 )`
by
`xfce? ( xfce-extra/tumbler[curl] )`
in xfce dependency line.

**Comment by Tatsh** [comment]
Thanks. Making the change.

**Comment by Tatsh** [comment]
https://github.com/Tatsh/tatsh-overlay/commit/e69e3839d962276595e7dfe9b79df6d66e0c408b
