### ISSUE TITLE
net-dns/pihole: does not exists /etc/init.d/pihole script

### ISSUE THREAD

**Issue by Bogdan107** [Tatsh/tatsh-overlay#119]
Command `pihole logging on` fails:
```
LC_ALL=en_US pihole logging on
  [i] Enabling logging...
/usr/bin/pihole: line 142: Cannot restart Pi-hole: command not found
  [✓] Logging has been enabled!
```
This is because `pihole` does not support OpenRC service manager. But if it support this in the future, then this init script must be present.

I use _OpenRC_ service manager. So, I write init script: [`/etc/init.d/pihole`](https://github.com/Tatsh/tatsh-overlay/files/7719197/pihole.txt).

Please, modify ebuild to add this init script:
1) add init script into `filesdir` directory near ebuild file;
2) add line to _src_install()_ of ebuild: `newinitd "${FILESDIR}/init-openrc" pihole`

As _Pihole_ and _Gentoo_ supports _Systemd_ service manager, then, please: add init script for _Systemd_ service manager too.
A lot of programs does not use `systemd` use flag, if all differents are in initialization script. So, no needs to improve `systemd` use flag to control which variant of init script install - just install both init scripts (_Systemd_ and _OpenRC_ variants).

**Comment by Bogdan107** [comment]
Feature reques of natively support of _OpenRC_ service manager by _Pi-Hole_ is posted at [pi-hole.net](https://discourse.pi-hole.net/t/add-support-of-openrc-service-manager/51630).

**Comment by Tatsh** [comment]
Sync again, re-emerge, and tell me if that init script works for you.

**Comment by Bogdan107** [comment]
## 1) Bug with _pidfile_ variable in init script of _OpenRC + pihole-FTL_

_OpenRC_ system use `pidfile` variable to configure started program where it must do a pid file. But _pihole-FTL_ program does not support this behaviour. Therefore _OpenRC_ or _pihole-FTL_ force use _/var/run/pihole-FTL.pid_ path.
I have symbolic link _/var/run -> /run_, and _OpenRC_ have some troubles, if value of _pidfile_ variable starts with _/var_ prefix. So, correct path for _pidfile_ - `/var/pihole-FTL.pid`.

As _pihole-FTL_ create `/var/run/pihole-FTL.pid` and /var/run/pihole-FTL.port` files themself, then _OpenRC_ mechanizm breaks to create pidfile at `/var/run/pihole-FTL.pid`.
If _pidfile_ variable have path, that different from _pihole-FTL_ do, then _rc-service pihole-FTL stop_ command fails with message _WARNING: pihole-FTL has already been started_.

Temporary solution:
1) use different name for `pidfile` variable;
2) use the same value of `pidfile` variable, as _pihole-FTL_ program create.

## 2) Add user/group veriables to init script
If user and group not specified in the init script, then _OpenRC_ starts binary with `root:root` permissions.

My last version of `/etc/init.d/pihole-FTL` file: [pihole-FTL](https://github.com/Tatsh/tatsh-overlay/files/7721466/pihole-ftl.openrc.txt).

**Comment by Tatsh** [comment]
I have not used OpenRC in ages, but I think you need to create a `start()` function and use `start-stop-daemon` with the `--make-pidfile` argument. Also remove the `command=` line. Also pass `--group` and `--user`.

https://wiki.gentoo.org/wiki/Handbook:X86/Working/Initscripts#Standard_functions

Did you make the symlink from `/var/run` to `/run`? I don't know if this is the default since a while ago, so I used `/var/run` in the OpenRC file. (systemd has `/var/run -> /run`.)

**Comment by Bogdan107** [comment]
`/var/run` symlinced to `/run` by distro maintainer.

I test this code:
```
...
#command="/usr/bin/pihole-FTL"
pidfile1="/run/pihole-FTL.pid"
...
start() {
  ebegin "Starting $name"
  start-stop-daemon --start --exec /usr/bin/pihole-FTL --pidfile "$pidfile1"
  eend $?
}
```

`pihole-FTL` starts normal. But `rc-service stop` just call _stop_post()_ and remove _/run/pihole*_, _/run/pihole/FTL.sock_ and _/dev/shm/FTL-*_ files. And `pihole-FTL` process still runed.
E.g. solution does not worked.

I think, that bug is inside hte `pihole-FTL` binary, not in the code of init script.

**Comment by Tatsh** [comment]
Please test the commit I just pushed.

**Comment by Bogdan107** [comment]
Work fine!

Some cosmetic changes:
```
...
# 1. add "-f" argument
checkpath --file-truncate -f "$PIFTL_PID"
...
# 1. add "/var" prefix
# 2. add "{/*,-FTL*}" specificator to delete only files, which created by pihole.
#     So /var/run/pihole-some-thing file will not to be deleted.
rm -rf /var/run/pihole{/*,-FTL*} /run/pihole/FTL.sock /dev/shm/FTL-*
...
```

**Comment by Tatsh** [comment]
Where did you get your `/etc/pihole/pihole-FTL.conf` file? My ebuilds don't install it. I want to make sure we are using the same paths in `/var/run` for `PIDFILE`, `PORTFILE`, `SOCKETFILE`. My file is like so:

```
# cat /etc/pihole/pihole-FTL.conf
DBFILE=/var/lib/pihole/pihole-FTL.db
GRAVITYDB=/var/lib/pihole/gravity.db
MACVENDORDB=/var/lib/pihole/macvendor.db
PIDFILE=/run/pihole/FTL.pid
PORTFILE=/run/pihole/FTL.port
SOCKETFILE=/run/pihole/FTL.sock
```

**Comment by Tatsh** [comment]
Also can't use `/var/run/pihole{/*,-FTL*}` because that is Bash-only. OpenRC scripts must be POSIX sh.

**Comment by Bogdan107** [comment]
I was create `/etc/pihole/pihole-FTL.conf` cleared, when receive message `Notice: Found no readable FTL config file` in syslog.

**Comment by Tatsh** [comment]
Okay. I have added a shipped version of `pihole-FTL.conf`. I think we have everything in the OpenRC init script?

**Comment by Bogdan107** [comment]
This is my current config, when `pihole-FTL` start/stop success, and resolve queies.
```
$ cat /etc/pihole/pihole-FTL.conf | grep -v -e "^#" -e "^$"
DBFILE=/var/lib/pihole/pihole-FTL.db
GRAVITYDB=/var/lib/pihole/gravity.db
MACVENDORDB=/var/lib/pihole/macvendor.db
PIDFILE=/var/run/pihole-FTL.pid
PORTFILE=/var/run/pihole/FTL.port
SOCKETFILE=/var/run/pihole/FTL.sock
BLOCKINGMODE=NULL
CNAME_DEEP_INSPECT=true
REPLY_WHEN_BUSY=REFUSE
MOZILLA_CANARY=true
BLOCK_ICLOUD_PR=true
SOCKET_LISTENING=localonly
RESOLVE_IPV6=yes
RESOLVE_IPV4=yes
NICE=-10
```

**Comment by Tatsh** [comment]
That's fine but you should update the variables to match mine for the ones we have that are the same:

```
DBFILE=/var/lib/pihole/pihole-FTL.db
GRAVITYDB=/var/lib/pihole/gravity.db
MACVENDORDB=/var/lib/pihole/macvendor.db
PIDFILE=/run/pihole/FTL.pid
PORTFILE=/run/pihole/FTL.port
SOCKETFILE=/run/pihole/FTL.sock
```

**Comment by Bogdan107** [comment]
I sync PIDFILE from pihole-FTL.conf with PIFTL_CMD from init script and all ok!
Service started and stopped by rc-service command!

Now my pidfile under _/var/run/pihole_ directory:
```
$ grep ^PIFTL_PID /etc/init.d/pihole-FTL
PIFTL_PID="/var/run/pihole/FTL.pid"
$ grep PIDFILE /etc/pihole/pihole-FTL.conf 
PIDFILE=/var/run/pihole/FTL.pid
```

**Comment by Bogdan107** [comment]
I switch PID path to `/run/pihole/FTL.pid`.

Delete _/var_ prefix from PIFTL_PID variable and from _stop_post_ function and I have no questions for OpenRC init script!

**Comment by Bogdan107** [comment]
!!!WARNING!!!

`pihole-FTL` program prepare database structure of `pihole-FTL.db` file, only if this file does not exists at `pihole-FTL` startup.
Therefore, the `pihole-FTL.db` and `pihole.db` files must not be created inside the init script - just chown-ed/chmod-ed if exists.

```
--- a/pihole-FTL  2021-12-16 00:38:43.140646096 +0200
+++ b/pihole-FTL  2021-12-16 05:12:29.472139143 +0200
@@ -24,15 +24,17 @@
                /run/pihole/FTL.port \
                /var/log/pihole-FTL.log \
                /var/log/pihole.log \
-               /var/lib/pihole/dhcp.leases \
-               /var/lib/pihole/pihole-FTL.db \
+               /var/lib/pihole/dhcp.leases
+       chown -f "$command_user" \
                /var/lib/pihole/gravity.db \
-               /var/lib/pihole/macvendor.db
+               /var/lib/pihole/pihole-FTL.db || ewarn "gravity.db or pihole-FTL.db is not properly installed"
+       chown -f "$command_user" \
+               /var/lib/pihole/macvendor.db || ewarn "macvendor.db file is not properly installed"
        # Prepare database file permissions so that the pihole group (web
        # interface) can edit the file.
-       checkpath -m 0664 -f \
-               /var/lib/pihole/pihole-FTL.db \
-               /var/lib/pihole/gravity.db
+       chmod -f 0644 \
+               /var/lib/pihole/gravity.db \
+               /var/lib/pihole/pihole-FTL.db || ewarn "gravity.db or pihole-FTL.db is not properly installed"
 }
 
 stop_post() {
```

This patch also resolve `Error: in prepare, no such table: queries` and `Error: in prepare, no such table: network_addresses` messages from #120.

**Comment by Bogdan107** [comment]
Also will be more likely with `provide dns` inside the `depend()` stage.

**Comment by Bogdan107** [comment]
Patch to select user and group rights in init script [pihole-FTL.openrc.patch](https://github.com/Tatsh/tatsh-overlay/files/7725323/pihole-FTL.openrc.patch.txt)
