### ISSUE TITLE
net-dns/pihole and net-dns/pihole: prepare *.db files by standard package manager command

### ISSUE THREAD

**Issue by Bogdan107** [Tatsh/tatsh-overlay#121]
This [pihole-5.6.ebuild-macvendor.db.patch](https://github.com/Tatsh/tatsh-overlay/files/7724697/pihole-5.6.ebuild-macvendor.db.patch.txt) allows to install `macvendor.db` file by standard package manager configuration command:
```
emerge net-dns/pihole --config
```

This [pihole-ftl-5.11.ebuild-gravity.db.patch](https://github.com/Tatsh/tatsh-overlay/files/7724698/pihole-ftl-5.11.ebuild-gravity.db.patch.txt) allows to prepare `gravity.db` database structure by standard package manager configuration command:
```
emerge net-dns/pihole-ftl --config
```

**Comment by Tatsh** [comment]
The first patch doesn't have `MACVENDOR_URI` defined. Also I do not think `pkg_config` should be called from `src_install`. Maybe it can be called from `pkg_postinst` but I thought `emerge --config` was to be run by the user separately.

**Comment by Bogdan107** [comment]
> The first patch doesn't have `MACVENDOR_URI` defined.
```
# Add this line after SRC_URI:
MACVENDOR_URI="https://ftl.pi-hole.net/macvendor.db"
```
Link from [https://programmersought.com/article/68718054610/](https://programmersought.com/article/68718054610/)

**Comment by Bogdan107** [comment]
Patch for ebuild: [pihole-5.6.ebuild-padd+macvendor+gravity.patch](https://github.com/Tatsh/tatsh-overlay/files/7729878/pihole-5.6.ebuild-padd%2Bmacvendor%2Bgravity.patch.txt)

**Comment by Tatsh** [comment]
This is done. PADD will be a separate package.
