### ISSUE TITLE
net-dns/pihole: add PADD use flag

### ISSUE THREAD

**Issue by Bogdan107** [Tatsh/tatsh-overlay#122]
[PADD](https://github.com/pi-hole/PADD) project improve more expansive version of the original `chronometer.sh`.

This patch allow to install `PADD` script instead of original `chronometer.sh`.

At now, current version 3.6.2 has some bugs. But with this [patch](https://github.com/pi-hole/PADD/issues/62#issuecomment-995455499) script is usable.

Patch attached: [pihole-5.6.ebuild-padd.patch](https://github.com/Tatsh/tatsh-overlay/files/7724969/pihole-5.6.ebuild-padd.sh.patch.txt)

**Comment by Tatsh** [comment]
I think this should be a separate package. Does it have to replace the `chronometer.sh` file in pihole? Why not type `padd` instead of `pihole -c`?

**Comment by Tatsh** [comment]
Try the package `app-admin/padd`.

**Comment by Tatsh** [comment]
The version issue is known about https://github.com/pi-hole/PADD/issues/157 but unfortunately did not get a fix.

**Comment by Tatsh** [comment]
New, patched package was added.
