### ISSUE TITLE
net-dns/pihole: implement autoupdate of macvendor.db

### ISSUE THREAD

**Issue by Bogdan107** [Tatsh/tatsh-overlay#123]
May be added some commented cronjob, which update `macvendor.db` once per month?
`ebuild` may contain `ewarn` or `einfo` message with `See /etc/cron.d/pihole to manual activation of automatic update of macvendor.db file`.

**Comment by Tatsh** [comment]
I need to know how often macvendor.db changes. Does Pi-hole in its normal installation download macvendor.db often?

**Comment by Tatsh** [comment]
Also note for me, implement:

- [ ] systemd timer for updating gravity.db
- [ ] systemd/cron timer for updating macvendor.db (if we do it)
