### ISSUE TITLE
app-vim/youcompleteme and its depends might be ready for python3_10 target

### ISSUE THREAD

**Issue by Universebenzene** [Tatsh/tatsh-overlay#134]
python3_10 target is stable now in the main tree, so ycm and its depends (including `dev-utils/ycmd` and `dev-python/requests-futures`) might be ready for upgrading to python3_10.

Also [this line](https://github.com/Tatsh/tatsh-overlay/blob/382fe0aaa237dcd2bcc790b3947aaa747550f74b/dev-util/ycmd/ycmd-20220111.ebuild#L47) might possibly need modifying for python3.10

**Comment by Tatsh** [comment]
Not going to put this on high priority yet as the default Python on my profile `default/linux/amd64/17.1/desktop/plasma/systemd` is still 3.9. I will accept PRs.

**Comment by Tatsh** [comment]
Closed via #135
