### ISSUE TITLE
Make an eclass for dotnet apps

### ISSUE THREAD

**Issue by Tatsh** [Tatsh/tatsh-overlay#146]
Would be used by ryujinx

**Comment by anna-cli** [comment]
Hello! If it helps, I made one (and commited to GURU dev) https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=bff17eaa33fa048bf6eca18d658b2cf5bea8d375

It's mainly based on your ryujinx ebuild and cargo.eclass. I used it for packaging xivlauncher for guru and it seems to work fine, would love some feedback tho!

**Comment by Tatsh** [comment]
I'm excited to try this.

**Comment by Tatsh** [comment]
This is very good! My Ryujinx ebuild can be reduced to just needing NUGETS and its own `src_install()`.

Feedback:

1. Can we do a Bash array for the `NUGETS` variable? `EGO_SUM` is done this way in the Go eclass (it may end up not being deprecated).
2. I'm thinking eventually there may be a desire to have the `--configuration` value change if the user specifies `USE=debug`. The other option is, IIRC, `Debug`. Projects can define their own configurations, however.
3. Maybe we should not hard-code `linux-x64` as there is an [ARM64 build of .NET](https://xhinker.medium.com/install-net-5-in-linux-step-by-step-478868105a33) available. I only did this in my ebuild because I don't think Ryujinx supports anything else.
4. I think we should not hard-code the dotnet version to `6.0`. Something > 6.0 is probably not far off from coming out.

**Comment by anna-cli** [comment]
Yay!

A string is how the cargo eclass does it so that's how I've done it. Tho I admit, an array might be a better option (And if there's any time to do it, it's now since the ebuild is still in dev and no one but me uses it in a guru package).

USE flag based NUGETs can be done by passing the list as an argument to nuget_uris() tho, array based arguments would require the user to pre-define those variables instead of just passing them with the call itself, I think. Don't know if this would be much of a problem tho.

2 & 3, yea. I am not a dotnet developer so I didn't know. virtual/dotnet-sdk *does* indeed support ~arm ~arm64, so that's a change to do already.

4 is me being dumb... It's my first ebuild/eclass so yea. (dotnet 7.0 is out already also)

**Comment by Tatsh** [comment]
Do you have an existing case where USE flag filtering in NUGETS is being done? .NET may be different from Go in that it may have more conditional builds. In that case, string should be kept. Go packages tend to not have any options at build time.

**Comment by anna-cli** [comment]
I asked on the XIV Launcher discord, dotnet does have variable nugets, as in set conditions to not download/compile some nugets in.

**Comment by Tatsh** [comment]
Okay then I think for simplicity keep `NUGETS` as a string so it can use the conditional syntax.

**Comment by anna-cli** [comment]
The main difference would be 
```
SRC_URI="
main.url
flag1? (
    $(nuget_uris "
        nuget-1.2
        nuget2-5.2
   ")
)
flat2? (
    $(nuget_uris "
        ...
    ")
)
"
```

vs

```
NUGET_FLAG1=( 'nuget-1.2', 'nuget2-5.3' )
NUGET_FLAG2=( ... )
SRC_URI="
    main.url
    flag1? ( $(nuget_uri ${NUGET_FLAG1}) )
    flag2? ( $(nuget_uri ${NUGET_FLAG2}) )
"
```

Tho, know I realise, if you want you can use an array by going:
```
NUGET_ARR=( 'nuget-1.4', 'nuget2-5.3' )
SRC_URI="$(nuget_uri ${NUGET_ARR[@]})" # or NUGET_ARR[*]
```

And you can also, obj, do example one with standalone variables the same was as two. (And I may be overthinking this)

**Comment by Tatsh** [comment]
The first one is better because everything can be a single expression. Bash arrays can't be done inside of a string because it's too ambiguous (syntax matches that of subshell).

**Comment by Tatsh** [comment]
Do you have a way to auto-generate `NUGETS`? It would be great if `csproj2ebuild` or something like that existed. The way I found the information was very careful inspection of the debug log while running `dotnet restore`.

**Comment by anna-cli** [comment]
I got a way to semi do it, that could be made in the script. First in a local copy we
`mkdir nuget && dotnet restore --packages nuget project.csproj`, and then do a loop for every folder, echo-ing `foldername-subfolder` for each subfolder. This will print every version restore.

We could also just look into the csproj, but the problem with that is the lack of dependencies of the dependencies, and runtime/system nugets.

I can write a bash script for the first option in like 5 minutes.

**Comment by Tatsh** [comment]
Iterating the directories seems to be the way to go. It would be nice to not have to download the tarballs for that, but small price to pay. Making a recursive dependency solver for .NET doesn't seem worthwhile just for this.

**Comment by anna-cli** [comment]
Found out it is also possible to `dotnet list project.csproj package --include-transient` and parse this output. But this one also requries to run restore beforehand, so downloading the tarballs are inevitable even with official tools. (If they do have a json api, it would be possible to avoid it acutally, but that begs the question of worthwhileness like you said)

**Comment by Tatsh** [comment]
Ryujinx really needs .NET 6.0 to build so I made the following change to your eclass:

```diff
diff --git a/eclass/dotnet-utils.eclass b/eclass/dotnet-utils.eclass
index 26a9680..d39e789 100644
--- a/eclass/dotnet-utils.eclass
+++ b/eclass/dotnet-utils.eclass
@@ -19,7 +19,7 @@ esac

 inherit multiprocessing

-BDEPEND=">=virtual/dotnet-sdk-6.0"
+BDEPEND="virtual/dotnet-sdk:${DOTNET_SLOT}"
 EXPORT_FUNCTIONS src_unpack src_prepare src_compile

 # @ECLASS_VARIABLE: DOTNET_CLI_TELEMETRY_OPTOUT
```

Then it has to be used like so:

```shell
DOTNET_SLOT="6.0"
inherit dotnet-utils
```

**Comment by anna-cli** [comment]
I'm gonna update the ebuild to include this (+ and error if the user doesn't set it), I'll also add support to arm64 and arm32.

**Comment by anna-cli** [comment]
Question: is `addpredict /opt/dotnet-sdk-bin-${DOTNET_RUNTIME}/metadata` really needed? My package is compiling fine without it...

**Comment by Tatsh** [comment]
Seems it is not needed anymore. Does this file or similar exist for you? `/opt/dotnet-sdk-bin-6.0/metadata/workloads/6.0.400/userlocal` Maybe try removing the `metadata` directory and see if the build still works without the addpredict?

**Comment by Tatsh** [comment]
Actually, no. That file really does belong to the package. So I think it was a bug in the past. Placing the file there manually as the ebuilds do removes the need for the addpredict.

**Comment by Tatsh** [comment]
I just realised you can only have 1 SDK installed at a time. If you install 7.0, it will uninstall 6.0. So I do not know how useful my change would actually be.

**Comment by anna-cli** [comment]
Each dotnet sdk is a different SLOT, you can have multiple versions installed.

**Comment by Tatsh** [comment]
Every time I install 6 or 7, it uninstalls the other. The virtual package doesn't care but the dotnet-sdk one does.

**Comment by anna-cli** [comment]
It's the opposite really. the virtual require dotnet-sdk[dotnet-symlink(+)], which you can't have two dotnet's with USE="dotnet-symlink". If you install them manually, without the virtual and with -dotnet-symlink, it allows it (it'll install the binaries `dotnet-bin-7.0` and `dotnet-bin-6.0`, instead of `dotnet`). I'll ask around on IRC if this is expected, if not, I might try to patch it.

**Comment by Tatsh** [comment]
Maybe add the include guard in the eclass? Not every eclass does but I think it's worth it to have.

**Comment by anna-cli** [comment]
The most recent eclass version on guru has a guard, and some other features, like slot picking, automatically detect between -bin and non-bin dotnet (tho I think this is a bit broken, I'll check and fix today or tomorrow if it is) (mind we don't rely on the virtual yet because of the bug from up there) and arm{,64} support (untested as I don't have any arm linux device)

https://gitweb.gentoo.org/repo/proj/guru.git/tree/eclass/dotnet-utils.eclass

**Comment by Tatsh** [comment]
Any luck on not needing `RESTRICT=strip`?

**Comment by Tatsh** [comment]
Closing as completed and I will try to keep up with updates on this eclass. Hopefully it gets into main tree soon and I won't have to.
