### ISSUE TITLE
x11-misc/rom-properties: Configuration tool missed

### ISSUE THREAD

**Issue by bell07** [Tatsh/tatsh-overlay#149]
x11-misc/rom-properties provides new tool "Rom Properties Configurator" (rp-config) I found in my XFCE menu, but does nothing. 
If I run it from command line, I get the 

```
 $ rp-config 
*** ERROR: Could not find rp_show_config_dialog() in any installed rom-properties plugin.
```

can you pls check ebuild if any new file is not installed? I installed it with
`USE="astc cli crypt gtk lz4 lzo nls pvr unice68 xbox-360 xfce xml zstd -achievements -kde -lto"`

**Comment by Tatsh** [comment]
Hmm. I have it working on KDE. I'm not sure if it is supposed to work on Gtk.

**Comment by bell07** [comment]
Just grep'ed the source. The rp-config seems kde and win32 only :-(
I think the file should not be installed if not compatible. The ebuild uses upstream installation routines, so it is an upstream bug

**Comment by Tatsh** [comment]
So it's not that simple to do due to the design. Best I can do easily is to remove the configurator .desktop file after the CMake script does its work `if ! use kde`.

**Comment by bell07** [comment]
In the next version maybe an gtk frontend appears. So the change should be `if ! use kde && ! use gtk` for the next version
