### ISSUE TITLE
Cemu broken

### ISSUE THREAD

**Issue by ps4boot** [Tatsh/tatsh-overlay#157]
i get an error on Cemu for run as user 

User have no right to write to /usr/bin 

before it was working.

thx for your packages.

**Comment by ps4boot** [comment]
maybe from the portable mod.

**Comment by Tatsh** [comment]
Yes I have put in a patch to fix this in the ebuild.

The settings will move so you either have to migrate settings or reconfigure. I don't think reconfiguration is too difficult so I didn't put a notice.
