### ISSUE TITLE
net-dns/pihole blockingpage.css was removed in 5.12

### ISSUE THREAD

**Issue by fawksie** [Tatsh/tatsh-overlay#159]
Hi Andrew

https://github.com/pi-hole/pi-hole/commit/6c9bd7a6328f892884b9e55064c61fa08b7682fe

As of upstream 5.12 advanced/blockingpage.css is no longer present and requires to be removed from the ebuild.

Sorry I'm not familiar with the workflow of contributing to an overlay (e.g. is it necessary to use pkgdev?) otherwise I'd submit a pull request.

**Comment by Tatsh** [comment]
It's not necessary to use pkgdev but it's highly preferred. It makes things easier. Also you should run 'pkgcheck scan' after changed especially because the manifest must always be up to date.

This change only applies if you are using the www flag which I'm not so I missed it.

**Comment by fawksie** [comment]
Thanks, I'll submit one shortly.
