### ISSUE TITLE
dbeaver-bin nitpicks 

### ISSUE THREAD

**Issue by PF4Public** [Tatsh/tatsh-overlay#164]
https://github.com/Tatsh/tatsh-overlay/blob/e73fc952413eb405276094d45a6db6791f9b421d/dev-db/dbeaver-bin/dbeaver-bin-22.2.4.ebuild#L42-L43

This fails if `dev-java/openjdk:11` is merged. Honestly saying I don't know what could be the proper fix.

BTW: does it support openjdk:17?

**Comment by Tatsh** [comment]
17 seems to work fine.

**Comment by PF4Public** [comment]
For non-bin jdk removing `-vm` parameter works just fine. Could it be, that it can find -bin jdk in the same manner?

**Comment by Tatsh** [comment]
Yes I was forcing version 11 (though I should have made it dynamic with regards to the path) because it's listed in the dependencies. I think I can just make it require virtual/jre:17 and not patch the script.
