### ISSUE TITLE
bug with libc++ and yuzu 

### ISSUE THREAD

**Issue by KonstantinDjairo** [Tatsh/tatsh-overlay#169]
yuzu is not compiling, and seems to be an error related to an environment variable
> https://github.com/yuzu-emu/yuzu/issues/141#issuecomment-364066531

here's the build.log, you can do a grep in 'FAILED'
[build.log](https://github.com/Tatsh/tatsh-overlay/files/10098652/build.log)

**Comment by Tatsh** [comment]
You're trying to build with GCC but with libc++ instead of libstdc++?

**Comment by Tatsh** [comment]
I really haven't tested GCC 13 and I don't really plan to until it's at least keyworded `~amd64`.

**Comment by KonstantinDjairo** [comment]
my default compiler is gcc, i didn't change anything for yuzu, it's all in the default compilation options, maybe i had to choose clang to compile this package?

**Comment by Tatsh** [comment]
You should try compiling with GCC 12 unless your intention is to use 13. In that case, you'll have to make patches.
