### ISSUE TITLE
games-emulation/cemu is currently broken

### ISSUE THREAD

**Issue by FellFromTheSky** [Tatsh/tatsh-overlay#171]
Hello Tatsh,
Wish you're going well.
I don't know if it also happens to you, but currently games-emulation/cemu refuses to build :
https://gist.github.com/7e6b31d44021f822dcf0722c128697a9
And I don't understand why since there's no reason given.
So should I report this to upstream or are you able to understand it and fix it?

**Comment by Tatsh** [comment]
I need a full build log. That log only contains errors regarding something else. I am assuming you're getting an error at linker stage as I am (just got it). Seems to be related to a Wayland symbol. Finding a fix now.

**Comment by FellFromTheSky** [comment]
Sorry, I was busy with a stupid programming homework.
Ok so, it seems to me wgetpaste wasn't able to p
[log.txt](https://github.com/Tatsh/tatsh-overlay/files/10203638/log.txt)
ost the whole log because there might be too much lines for GitHub Gist.
Then, look at the end of the build log, the content of it is about Cemu and not something else unlike the beginning of the build log.
Ok so, as you resquested here's the full build log :

**Comment by Tatsh** [comment]
If this occurs again please reopen.

**Comment by Tatsh** [comment]
Related: https://github.com/cemu-project/Cemu/issues/571 https://github.com/cemu-project/Cemu/pull/553

`wayland-client` should be somewhere in a `target_link_libraries` call either `CemuGui` or `CemuBin`. It should be made optional but for now it is not.

**Comment by FellFromTheSky** [comment]
It failed again.

[log.txt](https://github.com/Tatsh/tatsh-overlay/files/10203912/log.txt)

**Comment by Tatsh** [comment]
Wait a little for Gentoo mirror to update then sync again. Emerge @world and fmt should update first, then Cemu.

**Comment by FellFromTheSky** [comment]
Ok.

**Comment by Tatsh** [comment]
You can watch for mirror updates here: https://github.com/gentoo-mirror/tatsh-overlay

**Comment by Tatsh** [comment]
That error is not from building Cemu. The log shows it's from building opencascade. Please report that to Gentoo.

You should be able to update to 9.1.0 as almost everything that needed <9.1.0 is now updated (like Dolphin emulator). My Yuzu ebuild was blocking 9.1.0 which I considered highly detrimental as it was the only package doing that on my machines.

**Comment by FellFromTheSky** [comment]
Oh. Ok. I'll do.

**Comment by FellFromTheSky** [comment]
The Cemu package is still broken, it won't compile, even after the right version of VTK has been installed, it still believes it should use the previous version of VTK, see the logs \: 
https://gist.github.com/53a7abad9da23c639e2e6a99de6b8d5f

**Comment by Tatsh** [comment]
That is not the issue. Your issue is that fmt must be version 9.1.0. If something else is preventing that update you need to fix that.

**Comment by Tatsh** [comment]
The reason is because Cemu isn't asking your machine to update libfmt, and something else is blocking it from being upgraded. I can force Cemu to do that by updating the requirement. What is blocking libfmt? Try running `emerge -1pv =dev-libs/libfmt-9.1.0-r1` and paste the output here.

**Comment by FellFromTheSky** [comment]
No need. Apparently now everything is up to date, no preserved libraries except for libfmt because yuzu-9999::guru is currently broken.
