### ISSUE TITLE
RPCS3 fails to emerge because of Qt5::MultimediaWidgets

### ISSUE THREAD

**Issue by Caiowp** [Tatsh/tatsh-overlay#174]
When I try to emerge rpcs3 portage returns this:
CMake Error at 3rdparty/qt5.cmake:12 (target_link_libraries):
  The link interface of target "3rdparty_qt5" contains:

    Qt5::MultimediaWidgets

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:48 (include)

and I have dev-qt/qt5multimedia package installed

**Comment by Tatsh** [comment]
Can you post the output of

`qfile dev-qt/qt5multimedia | sort`

?

**Comment by Tatsh** [comment]
Also what USE flags are enabled for `dev-qt/qtmultimedia`?

**Comment by Caiowp** [comment]
> Also what USE flags are enabled for `dev-qt/qtmultimedia`?

ok, so that was the solution, widgets flag was not enabled, sorry for the incovenience!

**Comment by Tatsh** [comment]
This is important to note. I will update the ebuild. Thanks
