### ISSUE TITLE
www-apps/pihole-admin-lte PHP errors

### ISSUE THREAD

**Issue by LubosKolouch** [Tatsh/tatsh-overlay#176]
Hello,

Parse error: Unclosed '{' on line 17 in /var/www/localhost/htdocs/pihole-admin-lte/scripts/pi-hole/php/database.php on line 286

The installed database.php script gives error...

**Comment by LubosKolouch** [comment]
And also

Parse error: Unmatched '}' in /var/www/localhost/htdocs/pihole-admin-lte/scripts/pi-hole/php/footer.php on line 91

On the Clients page and 

Fatal error: Cannot redeclare convertseconds() (previously declared in /var/www/localhost/htdocs/pihole-admin-lte/scripts/pi-hole/php/func.php:706) in /var/www/localhost/htdocs/pihole-admin-lte/settings.php on line 573

On the DHCP page

There may be more. Are these upstream errors?

**Comment by Tatsh** [comment]
I don't think this is an upstream issue. I see the first issue but I am not getting the second. I am working now on the new patches.
