### ISSUE TITLE
CEMU ebuild not working with wxGTK 3.2.1 or stefantalpalaru 3.2.2.1-r300

### ISSUE THREAD

**Issue by kzdixon** [Tatsh/tatsh-overlay#178]
Original post: https://github.com/cemu-project/Cemu/issues/107#issuecomment-1433715494
Moving here for relevancy as requested.
Attempting to emerge `cemu`:
```
[ebuild  N     ] games-emulation/cemu-2.0_p20230208::tatsh-overlay  USE="cubeb sdl vulkan -discord" 0 KiB
```
results in:
```
-- Could NOT find wxWidgets (missing: wxWidgets_DIR)
^[[31mCMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES) (Required is at
  least version "3.2")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:977 (find_package_handle_standard_args)
  cmake/FindwxWidgets.cmake:17 (find_package)
  CMakeLists.txt:143 (find_package)

^[[0m
-- Configuring incomplete, errors occurred!
```
```bash
$ eselect wxwidgets show
Current wxWidgets profile:
  gtk3-unicode-3.2-gtk3
```
```
$ eqy wxGTK
Keywords for x11-libs/wxGTK:
                |                               |   u                |
                | a   a     p s     l r   a     |   n                |
                | m   r h   p p   i o i s l m m | e u s              | r
                | d a m p p c a x a o s 3 p 6 i | a s l              | e
                | 6 r 6 p p 6 r 8 6 n c 9 h 8 p | p e o              | p
                | 4 m 4 a c 4 c 6 4 g v 0 a k s | i d t              | o
----------------+-------------------------------+--------------------+----------------
     3.0.4-r5   | + + + ~ + + + + ~ o ~ o ~ o ~ | 8 o 3.0            | gentoo
----------------+-------------------------------+--------------------+----------------
[I]3.0.5.1-r1   | + + + ~ + + + + ~ ~ ~ o ~ o ~ | 7 o 3.0-gtk3       | gentoo
----------------+-------------------------------+--------------------+----------------
     3.2.1      | ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ o ~ o ~ | 8 o 3.2-gtk3       | gentoo
----------------+-------------------------------+--------------------+----------------
[I]3.2.2.1-r300 | ~ ~ ~ ~ ~ ~ ~ ~ ~ o ~ o ~ o ~ | 8 o 3.2-gtk3/3.2.2 | stefantalpalaru

```
Neither the suggested overlay's wxGTK nor 3.2.1 in the gentoo repository seem to satisfy the ebuild's search.

**Comment by Tatsh** [comment]
You do not have to change the profile to get this to merge. I do not know if it will be detrimental to keep on 3.2 so I leave it to 3.0. Only Cemu needs 3.2 but eselect does not help to make it find it.

Does the file `/usr/lib64/wx/config/gtk3-unicode-3.2-gtk3` exist on your machine? Is it executable?

Also, please attach the full log.

**Comment by Tatsh** [comment]
What it should look like:

```
 $ ls -la /usr/lib64/wx/config/gtk3-unicode-3.2-gtk3
-rwxr-xr-x 1 root root 49106 Feb 11 22:46 /usr/lib64/wx/config/gtk3-unicode-3.2-gtk3
```

**Comment by Tatsh** [comment]
Try the following commands and attach  the logs:

```
cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets 3.2 -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug.log
cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug-no-version.log
```

**Comment by kzdixon** [comment]
> Try the following commands and attach the logs:
> 
> ```
> cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets 3.2 -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug.log
> cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug-no-version.log
> ```
[cmake-debug.log](https://github.com/Tatsh/tatsh-overlay/files/10777970/cmake-debug.log)
[cmake-debug-no-version.log](https://github.com/Tatsh/tatsh-overlay/files/10777971/cmake-debug-no-version.log)

**Comment by Tatsh** [comment]
Are you using wxGTK from Gentoo or stefan? If the latter, switch to the Gentoo one as the overlay is no longer needed.

**Comment by kzdixon** [comment]
I get the same behavior on both; had originally trid the `gentoo` one and then tried the other one when it was initially suggested.
`gentoo`'s wxGTK is installed currently.

**Comment by Tatsh** [comment]
Need to re-run those commands post output, this time saving stderr.

```shell
cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets 3.2 -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug.log 2>&1
cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug-no-version.log 2>&1
```

**Comment by kzdixon** [comment]
> Need to re-run those commands and attach output, this time saving stderr.
> 
> ```shell
> cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets 3.2 -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug.log 2>&1
> cmake --debug-find-pkg=wxWidgets --find-package -DNAME=wxWidgets -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST > cmake-debug-no-version.log 2>&1
> ```
[cmake-debug.log](https://github.com/Tatsh/tatsh-overlay/files/10787305/cmake-debug.log)
[cmake-debug-no-version.log](https://github.com/Tatsh/tatsh-overlay/files/10787306/cmake-debug-no-version.log)

**Comment by Tatsh** [comment]
Need you to do something a little more complicated:

1. `cd /var/db/repos/tatsh/games-emulation/cemu` (or where it is)
1. edit the ebuild so it has the same debug argument passed to CMake:

```diff
diff --git a/games-emulation/cemu/cemu-2.0_p20230218.ebuild b/games-emulation/cemu/cemu-2.0_p20230218.ebuild
index 352573e..92c5701 100644
--- a/games-emulation/cemu/cemu-2.0_p20230218.ebuild
+++ b/games-emulation/cemu/cemu-2.0_p20230218.ebuild
@@ -66,6 +66,7 @@ src_configure() {
                -DPORTABLE=OFF
                -DwxWidgets_CONFIG_EXECUTABLE=/usr/$(get_libdir)/wx/config/gtk3-unicode-3.2-gtk3
                -Wno-dev
+               --debug-find-pkg=wxWidgets
        )
        cmake_src_configure
 }
```

2. Run `ebuild cemu-2.0_p20230218.ebuild manifest clean configure`
3. Post the build log.
4. `git checkout .` to reset the repository.

**Comment by kzdixon** [comment]
Sorry for the delay, nearly forgot to do this when I had time.
[build.log](https://github.com/Tatsh/tatsh-overlay/files/10808889/build.log)

**Comment by Tatsh** [comment]
Run `eselect wxwidgets set gtk3-unicode-3.2-gtk3` and post the log again.

**Comment by kzdixon** [comment]
[build.log](https://github.com/Tatsh/tatsh-overlay/files/10818897/build.log)
Different. Missing rapidjson apparently now?

**Comment by kzdixon** [comment]
> Run `eselect wxwidgets set gtk3-unicode-3.2-gtk3` and post the log again.

[build.log](https://github.com/Tatsh/tatsh-overlay/files/10818903/build.log)

**Comment by Tatsh** [comment]
I do not know what to do next here. You have a fairly customised setup and I think something in the environment is incorrect but it would be pointless to take more stabs at it I think. I cannot reproduce this issue and I have 2 systems detecting wxWidgets 3.2 (Gentoo's ebuild) without an issue.

You should grab the Cemu source and try building without Portage and see what the results are.

**Comment by FellFromTheSky** [comment]
I'm not sure if this is the same issue as his one, but it seems at least similar :
https://gist.github.com/520fa64ffb4f13afd097c9f860a7c904

**Comment by FellFromTheSky** [comment]
I finally replaced  x11-libs/wxGTK-3.2.2.1-r300::stefantalpalaru by x11-libs/wxGTK-3.2.2.1::gentoo.
It fixed sci-eletronics/kicad-7.0.0-r1::gentoo but not games-emulator/cemu::tatsh-overlay.

**Comment by Tatsh** [comment]
> I finally replaced x11-libs/wxGTK-3.2.2.1-r300::stefantalpalaru by x11-libs/wxGTK-3.2.2.1::gentoo. It fixed sci-eletronics/kicad-7.0.0-r1::gentoo but not games-emulator/cemu::tatsh-overlay.
> 
> Here's my current build failure logs : https://gist.github.com/fbd60cf13cea3b1760c692c48c537709

No this is not the same problem. Your wxWidgets 3.2 is getting found and you are getting past the configure phase. The issue you have is being resolved shortly.

**Comment by Tatsh** [comment]
@kzdixon I think I may have found the issue. Please update and try building again. Make sure you see the line `x11-libs/wxGTK:3.2-gtk3[opengl]` in the ebuild.

You can check with `qgrep 'x11-libs/wxGTK:3.2-gtk3[opengl]' cemu`.

**Comment by FellFromTheSky** [comment]
@Tatsh ok I see. Thanks a lot.

**Comment by kzdixon** [comment]
> @kzdixon I think I may have found the issue. Please update and try building again. Make sure you see the line `x11-libs/wxGTK:3.2-gtk3[opengl]` in the ebuild.
> 
> You can check with `qgrep 'x11-libs/wxGTK:3.2-gtk3[opengl]' cemu`.

Yep, that did it.

**Comment by Tatsh** [comment]
Thanks for the report.
