### ISSUE TITLE
games-emulation/cemu SDLController api cannot be set.

### ISSUE THREAD

**Issue by Loatchi** [Tatsh/tatsh-overlay#190]
When compiling cemu with USE="sdl" i'm expected to be able to use the SDL api to choose a controller however only DSUController can be selected.

**Comment by Tatsh** [comment]
I am not having this issue:

![image](https://github.com/Tatsh/tatsh-overlay/assets/724848/ba7a8cb2-2456-491e-a230-6eadc9b5f1e4)
![image](https://github.com/Tatsh/tatsh-overlay/assets/724848/9568a35e-3058-4aa6-8815-e2e2d8fd9c6b)

**Comment by Loatchi** [comment]
Ok I got it fixed.
I added USE="haptic" to libsdl2.

Try to recompile libsdl2 without said flag and see if you can reproduce the problem.
