### ISSUE TITLE
latest yuzu won't compile (1440)

### ISSUE THREAD

**Issue by camini** [Tatsh/tatsh-overlay#191]
hello
Was using the version before like a breeze and the new update won't compile.
[build.log](https://github.com/Tatsh/tatsh-overlay/files/11540936/build.log)

**Comment by Tatsh** [comment]
If you want an immediate fix, install `dev-util/vulkan-headers-1.3.246` and then try again.

The ebuild is updated now to reflect this requirement. Please wait a while and the gentoo-mirror copy will sync. Then try building again.
