### ISSUE TITLE
The overlay seem to no longer be compatible with a modern Gentoo system...

### ISSUE THREAD

**Issue by screening4ashes** [Tatsh/tatsh-overlay#192]
!!! Repository 'tatsh-overlay' is missing masters attribute in '/var/db/repos/tatsh-overlay/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
WARNING: One or more repositories have missing repo_name entries:

	/var/db/repos/tatsh-overlay/profiles/repo_name

NOTE: Each repo_name entry should be a plain text file containing a
unique name for the repository on the first line.

 * IMPORTANT: 2 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!
Dependency resolution took 2.04 s.

emerge: there are no binary packages to satisfy "games-emulation/ryujinx".

emerge: searching for similar names...
emerge: Maybe you meant any of these: games-emulation/zinc, games-emulation/higan, games-emulation/fceux?

**Comment by Tatsh** [comment]
I have the required file `metadata/layout.conf` correctly made. Are you sure this is not a permissions issue?

**Comment by screening4ashes** [comment]
I'm really not sure.... shouldn't be, I ran it as root.  The layout.conf
and the repo_name entries do not exist, but other folders and files are
created when enabling the overlay.  Any suggesting of commands to run to
check certain things?

**Comment by Tatsh** [comment]
Did you add the overlay with `eselect repository`? This is the recommended way and it's in the readme.

**Comment by Tatsh** [comment]
Do you have `tree` (`app-text/tree`) installed? Send the output of `tree -aphI .git /var/db/repos/tatsh-overlay`

**Comment by Tatsh** [comment]
`eselect` repository is for adding a custom repository and not picking from the list. You should only use `eselect repository enable tatsh-overlay`. If that fails, post the output.

You probably need to clean up the repository you cloned which is not the correct one. Maybe you can use `eselect remove -f tatsh-overlay` otherwise delete the directory and remove all mentions of tatsh-overlay from `/etc/portage/repos.conf/eselect-repo.conf`.

**Comment by screening4ashes** [comment]
that worked, thanks a lot! I now have ryujinx emerging, hopefully I have no
compile failures on that.
