### ISSUE TITLE
net-dns/pihole-ftl: pihole-FTL.db stays empty and is not usable on a  fresh install

### ISSUE THREAD

**Issue by dallenwilson** [Tatsh/tatsh-overlay#195]
On a fresh install of gentoo and pihole/pihole-FTL, I found that the `pihole-FTL.db` remained empty and unused, the only errors logged were regarding missing database tables. Eventually I found the cause:

The OpenRC init script installed by the ebuild at `/etc/init.d/pihole-FTL` performs several sanity-checks before launching the pihole-FTL daemon. The last check uses the `checkpath` command to verify that `/var/lib/pihole/pihole-FTL.db` has the correct file permissions. This is the source of the problem.

- If pihole-FTL starts and finds the database file is missing, it will create it and initialize the database with all the tables and other data.
- If it starts and finds the database file already exists, it skips the initialization and attempts to read the database.
- If a `checkpath` test on a file fails because the file does not exist, it creates the (empty) file.

The result of those three items is that launching pihole-FTL on a new install properly via rc-service leads to a situation where `pihole-FTL.db` is unusable.

I ran `rc-service pihole-FTL stop`, deleted `/var/lib/pihole/pihole-FTL.db`, commented out the last sanity check in `/etc/init.d/pihole-FTL`, and started it again with `rc-service pihole-FTL start` and the database was created, initialized and used correctly after that.

**Comment by Tatsh** [comment]
Can you make a PR for a fix? I think the fix would be like:

```shell
	{ [ -e /var/lib/pihole/gravity.db ] &&
          [ -e /var/lib/pihole/pihole-FTL.db ] &&
          checkpath -m 0664 -f \
		/var/lib/pihole/gravity.db \
		/var/lib/pihole/pihole-FTL.db; } || ewarn "gravity.db or pihole-FTL.db is not properly installed"
```

**Comment by Tatsh** [comment]
Better idea, check the size:

```shell
	{ [ -s /var/lib/pihole/gravity.db ] &&
          [ -s /var/lib/pihole/pihole-FTL.db ]; } &&
          checkpath -m 0664 -f \
		/var/lib/pihole/gravity.db \
		/var/lib/pihole/pihole-FTL.db || ewarn "gravity.db or pihole-FTL.db is not properly installed"
```
