### ISSUE TITLE
stepmania fails to build (ninja error)

### ISSUE THREAD

**Issue by teletrail** [Tatsh/tatsh-overlay#223]
hi, attempting to build stepmania from your overlay, however I get a build error with ninja during compilation.

log can be found here: 

http://0x0.st/H4vo.log

any advice would be appreciated.

**Comment by Tatsh** [comment]
Looks like an ffmpeg issue. What version do you have installed?

**Comment by teletrail** [comment]
media-video/ffmpeg-6.0-r6:0/58.60.60 currently installed.

 thanks for the prompt reply!

**Comment by Tatsh** [comment]
Unfortunately I haven't checked this, but more than likely it will only work with ffmpeg before version 5.

If you don't mind closed source, games-arcade/outfox is the successor.
