### ISSUE TITLE
net-dns/pihole-ftl-5.23-r2 fails during compile

### ISSUE THREAD

**Issue by CanuteTheGreat** [Tatsh/tatsh-overlay#235]
Hello,

While attempting to emerge net-dns/pihole-ftl-5.23-r2, it fails during compilation with this error:
[80/154] cd /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23_build/src/lua/scripts && RESOURCE_COMPILER-NOTFOUND -i < /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23/src/lua/scripts/inspect.lua > /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23/src/lua/scripts/inspect.lua.hex
FAILED: src/lua/scripts/inspect.lua.hex /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23_build/src/lua/scripts/inspect.lua.hex 
cd /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23_build/src/lua/scripts && RESOURCE_COMPILER-NOTFOUND -i < /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23/src/lua/scripts/inspect.lua > /var/tmp/portage/net-dns/pihole-ftl-5.23-r2/work/FTL-5.23/src/lua/scripts/inspect.lua.hex
/bin/sh: line 1: RESOURCE_COMPILER-NOTFOUND: command not found

See full build log:
[build.log](https://github.com/Tatsh/tatsh-overlay/files/13431888/build.log)

Thanks!

**Comment by Tatsh** [comment]
It needs xxd to be in PATH which you can get by installing vim-core. I am adding this to bdeps.
