### ISSUE TITLE
games-emulation/citra-20240121: Fetched file: citra-soundtouch-dd2252e.tar.gz VERIFY FAILED!

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [Tatsh/tatsh-overlay#264]
The ebuild fails to fetch citra-soundtouch-dd2252e.tar.gz because of a bad signature.
See the logs:
[citra-emerge-failure.txt](https://github.com/Tatsh/tatsh-overlay/files/14030364/citra-emerge-failure.txt)

**Comment by Tatsh** [comment]
Fixed with #260

**Comment by F3llFr0mTh3Sky** [comment]
Thanks a  lot.
