### ISSUE TITLE
games-emulation/rpcs3 - Request for a Patch to Avoid SIGABRTs

### ISSUE THREAD

**Issue by ThisNekoGuy** [Tatsh/tatsh-overlay#265]
Can we get this PR added as a patch here?

- https://github.com/RPCS3/rpcs3/pull/15095

**Comment by Tatsh** [comment]
Please use [user patches]() for now until the next release. I do not want to start the trend of adding requested patches here. Sometimes patches are incompatible with each other and I have my own way to manage the patches I do use (tools which have not been released yet).

**Comment by ThisNekoGuy** [comment]
I was asking both because you said in the other issue that the release you were using isn't up to date with upstream's git and you had said before you actually needed to rebase. The other reason was because there actually isn't a "download patch" button, for some reason, when I looked. I would have tried what you were suggesting if I was able to; which is weird, because usually the button is there for PRs. I was quite confused.

**Comment by Tatsh** [comment]
There's no longer a download button on GitHub. To get the patch file add `.patch` to the end of the URI after the number:

```
https://github.com/RPCS3/rpcs3/pull/15095.patch
```

So I would use (as root):

```shell
mkdir -p /etc/portage/patches/games-emulation/rpcs3
wget -O /etc/portage/patches/games-emulation/rpcs3/15095.patch 'https://github.com/RPCS3/rpcs3/pull/15095.patch'
```

**Comment by ThisNekoGuy** [comment]
Ughhhh, why would they remove that... Alright, I'll try it real quick

**Comment by ThisNekoGuy** [comment]
Yeah, the patch applies and works just fine. :+1:

**Comment by Tatsh** [comment]
Just remember when the next release comes the patch will fail so you'll need to delete it.
