### ISSUE TITLE
games-emulation/yuzu: Build Failure

### ISSUE THREAD

**Issue by shewdew** [Tatsh/tatsh-overlay#271]
I've posted an issue here once before with RPCS3 which I got lucky with figuring out it was a missing use flag for Qt, but this time I'm stuck with the build error just being "'optional’ is not a member of ‘std’" which isn't of much help since I'm not a Yuzu developer. I've tried downgrading boost from 1.84 to 1.82 since that's the only thing I could think of involving a C++ issue having been updated recently but it didn't help. I hope I'm not wasting your time missing something obvious, but I'm pretty much lost. Attached is the standard emerge info, build log, and emerge pqv.

[info.txt](https://github.com/Tatsh/tatsh-overlay/files/14278185/info.txt)
[build.log](https://github.com/Tatsh/tatsh-overlay/files/14278187/build.log)
[pqv.txt](https://github.com/Tatsh/tatsh-overlay/files/14278188/pqv.txt)

**Comment by Tatsh** [comment]
If you can edit the ebuild, try adding `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=OFF` in `src_configure()`. It looks more likely to be caused by Yuzu using precompiled headers which by default `cmake.eclass` disables.

**Comment by shewdew** [comment]
I'm happy to report that I copied the ebuild to a local repo, added that line (and remade the digest), and can say it works! I would not have ever been able to just figure that out on a whim, so many thanks good sir. Not sure if I should close this or if that change should be made to this repo, so I'll hold off and let you decide that one.

**Comment by Tatsh** [comment]
Thanks for testing. That sort of fix is just a temporary one for now. Going to apply it now.
