### ISSUE TITLE
games-emulation/yuzu-0.1734 - Fails archive.org Fetch

### ISSUE THREAD

**Issue by ThisNekoGuy** [Tatsh/tatsh-overlay#278]
The archive fetch fails as soon as the emerge begins:

[emerge_yuzu_build.log](https://github.com/Tatsh/tatsh-overlay/files/14502591/emerge_yuzu_build.log)

**Comment by Tatsh** [comment]
It looks like you have a custom fetch command. It needs to be allowed to follow redirects.

**Comment by Tatsh** [comment]
I am going to change to that for convenience.

I did run a fetch on a system that has never seen yuzu and it worked fine though the redirects were a bit slow. Is it timing out on your end?

**Comment by yretenai** [comment]
Citra fails for me, the hash differs. Manually downloading it confirms that the hash is different.

```
mine = 3e09c0d32f1e5d19fa67f44faabed130c69d3891691b52e33e2204cfcf21071ed5e5cf90eb7a8c3f2594f1b972e90af3af54176bbbb3793600a0355130aae77d
here = 01ad7af393d7a3c99c1b85ccb9e6de31b510373165980756ed57c8fdcc4e4e795dd801d30e8192c646e181b1cb1d00f547dba492ded13781fd268a85be4b7752
```

**Comment by Tatsh** [comment]
@ThisNekoGuy Please verify Yuzu is okay now and close if so.

@F3llFr0mTh3Sky the date on the compatibility list is 2023-11-11 so it's not very outdated. The [new fork](https://github.com/PabloMK7/citra) of Citra will have updates as necessary.

**Comment by ThisNekoGuy** [comment]
> Please verify Yuzu is okay now and close if so.

Yuzu fetches now

**Comment by ThisNekoGuy** [comment]
Not sure why but this build is running abnormally slow for me, even just loading Yuzu's native menus; it "works" but I didn't have this slowdown with 0.1733
Not sure what caused such a significant slowdown between the two
