### ISSUE TITLE
net-dns/pihole-ftl-5.25.2-r1 failed (postinst phase)

### ISSUE THREAD

**Issue by raffaele-ghb** [Tatsh/tatsh-overlay#360]
Happens cross-compiling for ~arm64. On the HOST:

* Call stack:
 *     ebuild.sh, line  136:  Called pkg_postinst
 *   environment, line 2154:  Called fcaps_pkg_postinst
 *   environment, line 1426:  Called fcaps 'cap_net_bind_service' 'cap_net_admin' 'cap_net_raw' 'cap_sys_nice' 'usr/bin/pihole-FTL'
 *   environment, line 1394:  Called die
 * The specific snippet of code:
 *               chmod ${caps_mode} "${file}" || die;

From the build-log:
>>> Safely unmerging already-installed instance...
>>> Original instance of package unmerged safely.
chmod: cannot access '/usr/aarch64-unknown-linux-gnu/cap_net_admin': No such file or directory

Installation of the binary package on the TARGET issues a similar same error:
>>> Safely unmerging already-installed instance...
>>> Original instance of package unmerged safely.
chmod: cannot access '/cap_net_admin': No such file or directory

The file on the TARGET has the correct capabilities regardless the error (but this is an update so they may be set from a previous install):
# getcap /usr/bin/pihole-FTL 
/usr/bin/pihole-FTL cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_nice=eip

**Comment by Tatsh** [comment]
Should be good now.

**Comment by raffaele-ghb** [comment]
Confirmed, thanks
