### ISSUE TITLE
app-misc/czkawka-7.0.0 not mergeable.

### ISSUE THREAD

**Issue by RayOfLight1** [Tatsh/tatsh-overlay#372]
Your app-misc/czkawka ebuild contains a hard coded list of crates to build it.
It is currently unmergeable because it requires time-0.3.34 which makes it not able to be compiled.

This issue is solved by requiring time-0.3.36

Thank you

**Comment by Tatsh** [comment]
That is strange. The version that 7.0.0 is locked to is 0.3.34.

https://github.com/qarmin/czkawka/blob/7.0.0/Cargo.lock#L5679

**Comment by RayOfLight1** [comment]
Check https://github.com/qarmin/czkawka/pull/1354/commits/90ef3a664394013ef131576997b31c5a3fd77933

I don't know why it is different, maybe we are seeing a different branch?

**Comment by Tatsh** [comment]
What is the error you're getting from Portage?

**Comment by Tatsh** [comment]
I think this has been fixed in #383
